// service
export const FETCH_SERVICES_PENDING = 'FETCH_SERVICES_PENDING'
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE'

export const CREATE_PROXYPASS_PENDING = 'CREATE_PROXYPASS_PENDING'
export const CREATE_PROXYPASS_SUCCESS = 'CREATE_PROXYPASS_SUCCESS'
export const CREATE_PROXYPASS_FAILURE = 'CREATE_PROXYPASS_FAILURE'
